### ISSUE TITLE
UG and Feature mismatch

### ISSUE THREAD

**Issue by ameliatjy** [AY2021S1-CS2103T-T17-3/tp#161]
The UG example of: add job n/Waiter c/Amelia’s Eating House p/98765432 e/ameliatjy@example.com 
a/Amelia Street, Block 123, #01-01 pr/low t/MultipleLocations v/1
is an invalid input.
![image](https://user-images.githubusercontent.com/65386073/97513868-4b280680-19c8-11eb-937b-4ced1619e62a.png)

Possible follow up actions:
1. Edit UG
2. Edit allowable Name inputs

**Comment by raythx98** [comment]
Suggest

1. Edit UG
2. maybe a change c/ (and maybe n/) to a subclass of name that allows apostrophe and other weird stuff?
