### ISSUE TITLE
SmokeTest: Suggestion to have smth on the right on loadup

### ISSUE THREAD

**Issue by Marcon2509** [AY2021S1-CS2103T-T17-3/tp#313]
![image](https://user-images.githubusercontent.com/69384485/98458262-c7d99280-21c9-11eb-9444-cd715952c0ee.png)
minor issue but when i loaded it up i tot the right side was missing cause it completely blank maybe have a default image there

**Comment by vanGoghhh** [comment]
Closed by #316
